train_data = [
    ("These mountains were the domain of House Arryn, and the late Hands widow was a Tully, Catelyn Starks sister...", 
     {"entities": [(32, 43, "HOUSE"), (71, 76, "HOUSE"), (78, 92, "PERSON")]}),
    ("...and no friend to the Lannisters.", 
     {"entities": [(21, 31, "HOUSE")]}),
    ("Tyrion had known the Lady Lysa slightly during her years at Kings Landing, and did not look forward to renewing the acquaintance.", 
     {"entities": [(0, 6, "PERSON"), (21, 31, "TITLE"), (32, 36, "PERSON"), (61, 74, "LOCATION")]}),
    ("His captors were clustered around a stream a short ways down the high road.", 
     {"entities": []}),
    ("The horses had drunk their fill of the icy cold water, and were grazing on clumps of brown grass that grew from clefts in the rock.", 
     {"entities": []}),
    ("Jyck and Morrec huddled close, sullen and miserable.", 
     {"entities": [(0, 4, "PERSON"), (9, 15, "PERSON")]}),
    ("Mohor stood over them, leaning on his spear and wearing a rounded iron cap that made him look as if he had a bowl on his head.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Nearby, Marillion the singer sat oiling his woodharp, complaining of what the damp was doing to his strings.", 
     {"entities": [(9, 18, "PERSON"), (23, 29, "TITLE"), (40, 48, "OBJECT")]}),
    ("We must have some rest, my lady, the hedge knight Ser Willis Wode was saying to Catelyn Stark as Tyrion approached.", 
     {"entities": [(34, 41, "TITLE"), (42, 56, "PERSON"), (60, 72, "PERSON"), (76, 82, "PERSON")]}),
    ("He was Lady Whents man, stiff-necked and stolid, and the first to rise to aid Catelyn Stark back at the inn.", 
     {"entities": [(7, 17, "TITLE"), (18, 23, "HOUSE"), (51, 63, "PERSON")]}),
    ("Ser Willis speaks truly, my lady, Ser Rodrik said.", 
     {"entities": [(0, 9, "TITLE"), (10, 16, "PERSON"), (38, 48, "TITLE"), (49, 55, "PERSON")]}),
    ("This is the third horse we have lost.", 
     {"entities": []}),
    ("We will lose more than horses if were overtaken by the Lannisters, she reminded them.", 
     {"entities": [(54, 64, "HOUSE")]}),
    ("Her face was windburnt and gaunt, but it had lost none of its determination.", 
     {"entities": []}),
    ("Small chance of that here, Tyrion put in.", 
     {"entities": [(26, 32, "PERSON")]}),
    ("The lady did not ask your views, dwarf, snapped Kurleket, a great fat oaf with short- cropped hair and a pigs face.", 
     {"entities": [(46, 54, "PERSON")]}),
    ("He was one of the Brackens, a man-at-arms in the service of Lord Jonos.", 
     {"entities": [(18, 26, "HOUSE"), (52, 57, "TITLE"), (58, 63, "PERSON")]}),
    ("Tyrion had made a special effort to learn all their names, so he might thank them later for their tender treatment of him.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("A Lannister always paid his debts.", 
     {"entities": [(2, 11, "HOUSE")]}),
    ("Kurleket would learn that someday, as would his friends Lharys and Mohor, and the good Ser Willis, and the sellswords Bronn and Chiggen.", 
     {"entities": [(0, 8, "PERSON"), (38, 44, "PERSON"), (49, 54, "PERSON"), (70, 80, "TITLE"), (81, 87, "PERSON"), (105, 110, "PERSON"), (115, 122, "PERSON")]}),
# ]
# train_data = [
    ("Arya stood rooted to the spot.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Nothing bads happened to Jon, has it? she asked Yoren.", 
     {"entities": [(25, 28, "PERSON"), (43, 48, "PERSON")]}),
    ("Or Uncle Benjen?", 
     {"entities": [(9, 15, "PERSON")]}),
    ("Well, as to Stark, I cant say.", 
     {"entities": [(10, 15, "HOUSE")]}),
    ("The Snow boy was well enough when I left the Wall.", 
     {"entities": [(4, 8, "HOUSE"), (41, 49, "LOCATION")]}),
    ("Its not them as concerns me.", 
     {"entities": []}),
    ("Desmond took her hand.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Come along, milady. You heard your lord father.", 
     {"entities": [(13, 19, "TITLE")]}),
    ("Arya had no choice but to go with him, wishing it had been Fat Tom.", 
     {"entities": [(0, 4, "PERSON"), (46, 53, "PERSON")]}),
    ("With Tom, she might have been able to linger at the door on some excuse and hear what Yoren was saying, but Desmond was too single-minded to trick.", 
     {"entities": [(5, 8, "PERSON"), (75, 80, "PERSON"), (86, 93, "PERSON")]}),
    ("How many guards does my father have? she asked him as they descended to her bedchamber.", 
     {"entities": []}),
    ("Here at Kings Landing? Fifty.", 
     {"entities": [(9, 22, "LOCATION")]}),
    ("You wouldnt let anyone kill him, would you? she asked.", 
     {"entities": []}),
    ("Desmond laughed.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("No fear on that count, little lady. Lord Eddards guarded night and day.", 
     {"entities": [(32, 36, "TITLE"), (37, 43, "PERSON")]}),
    ("Hell come to no harm.", 
     {"entities": []}),
    ("The Lannisters have more than fifty men, Arya pointed out.", 
     {"entities": [(4, 14, "HOUSE"), (41, 45, "PERSON")]}),
    ("So they do, but every northerner is worth ten of these southron swords, so you can sleep easy.", 
     {"entities": []}),
    ("What if a wizard was sent to kill him?", 
     {"entities": [(12, 18, "TITLE")]}),
    ("Well, as to that, Desmond replied, drawing his longsword, wizards die the same as other men, once you cut their heads off.", 
     {"entities": [(14, 21, "PERSON"), (40, 49, "OBJECT")]}),
# ]
# train_data = [
    ("Ser Jorah Mormont said, The Western Market will have food more to your taste, Your Grace.", 
     {"entities": [(0, 15, "PERSON"), (21, 37, "LOCATION"), (61, 71, "TITLE")]}),
    ("The traders from the Free Cities come there to sell their wares.", 
     {"entities": [(21, 32, "LOCATION")]}),
    ("The khal will honor his promise in his own time.", 
     {"entities": [(4, 8, "TITLE")]}),
    ("He had better, Viserys said grimly.", 
     {"entities": [(13, 20, "PERSON")]}),
    ("I was promised a crown, and I mean to have it.", 
     {"entities": [(19, 24, "OBJECT")]}),
    ("The dragon is not mocked.", 
     {"entities": [(4, 10, "PSEUDONYM")]}),
    ("Spying an obscene likeness of a woman with six breasts and a ferrets head, he rode off to inspect it more closely.", 
     {"entities": []}),
    ("Dany was relieved, yet no less anxious.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("I pray that my sun-and-stars will not keep him waiting too long, she told Ser Jorah when her brother was out of earshot.", 
     {"entities": [(44, 49, "TITLE"), (60, 75, "PERSON")]}),
    ("The knight looked after Viserys doubtfully.", 
     {"entities": [(18, 25, "PERSON")]}),
    ("Your brother should have bided his time in Pentos.", 
     {"entities": [(38, 44, "LOCATION")]}),
    ("There is no place for him in a khalasar.", 
     {"entities": [(30, 38, "LOCATION")]}),
    ("Illyrio tried to warn him.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("He will go as soon as he has his ten thousand.", 
     {"entities": []}),
    ("My lord husband promised a golden crown.", 
     {"entities": [(3, 7, "TITLE"), (27, 33, "OBJECT")]}),
    ("Ser Jorah grunted.", 
     {"entities": [(0, 9, "PERSON")]}),
    ("Yes, Khaleesi, but... the Dothraki look on these things differently than we do in the west.", 
     {"entities": [(5, 13, "TITLE"), (20, 28, "RACE")]}),
    ("I have told him as much, as Illyrio told him, but your brother does not listen.", 
     {"entities": [(27, 34, "PERSON")]}),
    ("The horselords are no traders.", 
     {"entities": [(4, 14, "RACE")]}),
    ("Viserys thinks he sold you, and now he wants his price.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Yet Khal Drogo would say he had you as a gift.", 
     {"entities": [(4, 14, "PERSON")]}),
    ("He will give Viserys a gift in return, yes... in his own time.", 
     {"entities": [(13, 20, "PERSON")]}),
    ("You do not demand a gift, not of a khal.", 
     {"entities": [(30, 34, "TITLE")]}),
    ("You do not demand anything of a khal.", 
     {"entities": [(30, 34, "TITLE")]}),
    ("It is not right to make him wait.", 
     {"entities": []}),
    ("Dany did not know why she was defending her brother, yet she was.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Viserys says he could sweep the Seven Kingdoms with ten thousand Dothraki screamers.", 
     {"entities": [(0, 7, "PERSON"), (26, 40, "LOCATION"), (55, 63, "RACE")]}),
    ("Ser Jorah snorted.", 
     {"entities": [(0, 9, "PERSON")]}),
    ("Viserys could not sweep a stable with ten thousand brooms.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Dany could not pretend to surprise at the disdain in his tone.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("What... what if it were not Viserys? she asked.", 
     {"entities": [(26, 33, "PERSON")]}),
    ("If it were someone else who led them? Someone stronger?", 
     {"entities": []}),
    ("Could the Dothraki truly conquer the Seven Kingdoms?", 
     {"entities": [(10, 18, "RACE"), (39, 53, "LOCATION")]}),
# ] # <<<< WORK UNTIL HERE
# train_data = [
    ("The master of the Kings Galley White Hart plots to slip anchor three days hence to offer his sword and ship to Lord Stannis.", 
     {"entities": [(16, 29, "TITLE"), (30, 40, "OBJECT"), (74, 85, "PERSON")]}),
    ("Tyrion sighed.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("I suppose we must make some sort of bloody lesson out of the man?", 
     {"entities": []}),
    ("Ser Jacelyn could arrange for him to vanish, but a trial before the king would help assure the continued loyalty of the other captains.", 
     {"entities": [(0, 10, "PERSON"), (40, 44, "TITLE")]}),
    ("And keep my royal nephew occupied as well.", 
     {"entities": []}),
    ("As you say. Put him down for a dose of Joffreys justice.", 
     {"entities": [(36, 44, "PERSON")]}),
    ("Varys made a mark on the parchment.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Ser Horas and Ser Hobber Redwyne have bribed a guard to let them out of a postern gate, the night after next.", 
     {"entities": [(0, 9, "PERSON"), (14, 26, "PERSON")]}),
    ("Arrangements have been made for them to sail on the Pentoshi galley Moonrunner, disguised as oarsmen.", 
     {"entities": [(46, 54, "LOCATION"), (62, 72, "OBJECT")]}),
    ("Can we keep them on those oars for a few years, see how they fancy it?", 
     {"entities": []}),
    ("He smiled.", 
     {"entities": []}),
    ("No, my sister would be distraught to lose such treasured guests.", 
     {"entities": []}),
    ("Inform Ser Jacelyn. Seize the man they bribed and explain what an honor it is to serve as a brother of the Nights Watch.", 
     {"entities": [(7, 17, "PERSON"), (88, 100, "ORGANIZATION")]}),
    ("And have men posted around the Moonrunner, in case the Redwynes find a second guard short of coin.", 
     {"entities": [(28, 38, "OBJECT"), (48, 56, "FAMILY")]}),
    ("As you will.", 
     {"entities": []}),
    ("Another mark on the parchment.", 
     {"entities": []}),
    ("Your man Timett slew a winesellers son this evening, at a gambling den on the Street of Silver.", 
     {"entities": [(9, 15, "PERSON"), (67, 84, "LOCATION")]}),
    ("He accused him of cheating at tiles.", 
     {"entities": []}),
    ("Was it true?", 
     {"entities": []}),
    ("Oh, beyond a doubt.", 
     {"entities": []}),
    ("Then the honest men of the city owe Timett a debt of gratitude.", 
     {"entities": [(33, 39, "PERSON")]}),
    ("I shall see that he has the kings thanks.", 
     {"entities": [(28, 33, "TITLE")]}),
    ("The eunuch gave a nervous giggle and made another mark.", 
     {"entities": []}),
    ("We also have a sudden plague of holy men.", 
     {"entities": []}),
    ("The comet has brought forth all manner of queer priests, preachers, and prophets, it would seem.", 
     {"entities": []}),
    ("They beg in the winesinks and pot-shops and foretell doom and destruction to anyone who stops to listen.", 
     {"entities": []}),
    ("Tyrion shrugged.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("We are close on the three hundredth year since Aegons Landing, I suppose it is only to be expected.", 
     {"entities": [(45, 58, "EVENT")]}),
    ("Let them rant.", 
     {"entities": []}),
    ("They are spreading fear, my lord.", 
     {"entities": []}),
    ("I thought that was your job.", 
     {"entities": []}),
    ("Varys covered his mouth with his hand.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("You are very cruel to say so.", 
     {"entities": []}),
    ("One last matter.", 
     {"entities": []}),
    ("Lady Tanda gave a small supper last night.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("I have the menu and the guest list for your inspection.", 
     {"entities": []}),
    ("When the wine was poured, Lord Gyles rose to lift a cup to the king, and Ser Balon Swann was heard to remark, Well need three cups for that.", 
     {"entities": [(31, 41, "PERSON"), (61, 77, "PERSON")]}),
# ]
# train_data = [
    ("Your eunuch must have told you, there is small love for the Lannisters in Kings Landing.", 
     {"entities": [(33, 43, "FAMILY"), (47, 59, "LOCATION")]}),
    ("Many still remember how your lord father sacked the city, when Aerys opened the gates to him.", 
     {"entities": [(63, 68, "PERSON")]}),
    ("They whisper that the gods are punishing us for the sins of your Housefor your brothers murder of King Aerys, for the butchery of Rhaegars children, for the execution of Eddard Stark and the savagery of Joffreys justice.", 
     {"entities": [(50, 68, "TITLE"), (90, 97, "PERSON"), (128, 140, "PERSON"), (159, 167, "PERSON")]}),
    ("Some talk openly of how much better things were when Robert was king, and hint that times would be better again with Stannis on the throne.", 
     {"entities": [(45, 51, "PERSON"), (95, 102, "PERSON")]}),
    ("In pot-shops and winesinks and brothels, you hear these thingsand in the barracks and guardhalls as well, I fear.", 
     {"entities": []}),
    ("They hate my family, is that what you are telling me?", 
     {"entities": []}),
    ("Aye... and will turn on them, if the chance comes.", 
     {"entities": []}),
    ("Me as well? Ask your eunuch.", 
     {"entities": []}),
    ("Im asking you.", 
     {"entities": []}),
    ("Bywaters deep-set eyes met the dwarfs mismatched ones, and did not blink.", 
     {"entities": [(0, 8, "PERSON")]}),
    ("You most of all, my lord.", 
     {"entities": []}),
    ("Most of all? The injustice was like to choke him.", 
     {"entities": []}),
    ("It was Joffrey who told them to eat their dead, Joffrey who set his dog on them.", 
     {"entities": [(8, 15, "PERSON"), (45, 52, "PERSON")]}),
    ("How could they blame me?", 
     {"entities": []}),
    ("His Grace is but a boy.", 
     {"entities": [(4, 9, "TITLE")]}),
    ("In the streets, it is said that he has evil councilors.", 
     {"entities": []}),
    ("The queen has never been known as a friend to the commons, nor is Lord Varys called the Spider out of love...", 
     {"entities": [(4, 9, "TITLE"), (56, 66, "TITLE"), (67, 72, "PERSON")]}),
    ("but it is you they blame most.", 
     {"entities": []}),
    ("Your sister and the eunuch were here when times were better under King Robert, but you were not.", 
     {"entities": [(70, 75, "TITLE"), (76, 82, "PERSON")]}),
    ("They say that youve filled the city with swaggering sellswords and unwashed savages, brutes who take what they want and follow no laws but their own.", 
     {"entities": []}),
    ("They say you exiled Janos Slynt because you found him too bluff and honest for your liking.", 
     {"entities": [(18, 29, "PERSON")]}),
    ("They say you threw wise and gentle Pycelle into the dungeons when he dared raise his voice against you.", 
     {"entities": [(28, 35, "PERSON")]}),
    ("Some even claim that you mean to seize the Iron Throne for your own.", 
     {"entities": [(34, 45, "OBJECT")]}),
# ]
# train_data = [
    ("Ser Rodrik had needed every man of fighting age he could lay his hands on, so Winterfell had been left with only a token garrison.", 
     {"entities": [(4, 10, "PERSON"), (61, 71, "LOCATION")]}),
    ("The rest had left eight days past, six hundred men from Winterfell and the nearest holdfasts.", 
     {"entities": [(51, 61, "LOCATION")]}),
    ("Cley Cerwyn was bringing three hundred more to join them on the march, and Maester Luwin had sent ravens before them, summoning levies from White Harbor and the barrowlands and even the deep places inside the wolfswood.", 
     {"entities": [(0, 11, "PERSON"), (55, 68, "TITLE"), (69, 74, "PERSON"), (108, 120, "LOCATION"), (129, 140, "LOCATION"), (169, 178, "LOCATION")]}),
    ("Torrhens Square was under attack by some monstrous war chief named Dagmer Cleftjaw.", 
     {"entities": [(0, 15, "LOCATION"), (62, 77, "PERSON")]}),
    ("Old Nan said he couldnt be killed, that once a foe had cut his head in two with an axe, but Dagmer was so fierce hed just pushed the two halves back together and held them until they healed up.", 
     {"entities": [(0, 7, "PERSON"), (77, 83, "PERSON")]}),
    ("Could Dagmer have won?", 
     {"entities": [(6, 12, "PERSON")]}),
    ("Torrhens Square was many days from Winterfell, yet still...", 
     {"entities": [(0, 15, "LOCATION"), (35, 45, "LOCATION")]}),
    ("Bran pulled himself from the bed, moving bar to bar until he reached the windows.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("His fingers fumbled a little as he swung back the shutters.", 
     {"entities": []}),
    ("The yard was empty, and all the windows he could see were black.", 
     {"entities": []}),
    ("Winterfell slept.", 
     {"entities": [(0, 10, "LOCATION")]}),
    ("Hodor! he shouted down, as loud as he could.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Hodor would be asleep above the stables, but maybe if he yelled loud enough hed hear, or somebody would.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Hodor, come fast! Osha! Meera, Jojen, anyone!", 
     {"entities": [(0, 5, "PERSON"), (18, 22, "PERSON"), (24, 29, "PERSON"), (31, 36, "PERSON")]}),
    ("Bran cupped his hands around his mouth.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("HOOOOODOOOOOR!", 
     {"entities": []}),
    ("But when the door crashed open behind him, the man who stepped through was no one Bran knew.", 
     {"entities": [(68, 72, "PERSON")]}),
    ("He wore a leather jerkin sewn with overlapping iron disks, and carried a dirk in one hand and an axe strapped to his back.", 
     {"entities": []}),
    ("What do you want? Bran demanded, afraid.", 
     {"entities": [(16, 20, "PERSON")]}),
    ("This is my room. You get out of here.", 
     {"entities": []}),
    ("Theon Greyjoy followed him into the bedchamber.", 
     {"entities": [(0, 13, "PERSON")]}),
    ("Were not here to harm you, Bran.", 
     {"entities": [(27, 31, "PERSON")]}),
    ("Theon? Bran felt dizzy with relief.", 
     {"entities": [(0, 5, "PERSON"), (7, 11, "PERSON")]}),
    ("Did Robb send you? Is he here too?", 
     {"entities": [(4, 8, "PERSON")]}),
    ("Robbs far away. He cant help you now.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Help me? He was confused.", 
     {"entities": []}),
    ("Dont scare me, Theon.", 
     {"entities": [(17, 22, "PERSON")]}),
    ("Im Prince Theon now.", 
     {"entities": [(4, 16, "TITLE_PERSON")]}),
    ("Were both princes, Bran.", 
     {"entities": [(19, 23, "PERSON")]}),
    ("Who would have dreamed it? But Ive taken your castle, my prince.", 
     {"entities": []}),
    ("Winterfell? Bran shook his head.", 
     {"entities": [(0, 10, "LOCATION"), (12, 16, "PERSON")]}),
    ("No, you couldnt. Leave us, Werlag.", 
     {"entities": [(27, 33, "PERSON")]}),
# ]
# train_data = [
    ("Castle Black seemed as much a ruin as Greyguard.", 
     {"entities": [(0, 12, "LOCATION"), (35, 44, "LOCATION")]}),
    ("Brown brittle weeds grew between cracks in the stones of the courtyards.", 
     {"entities": []}),
    ("Old snow covered the roof of the Flint Barracks and lay in drifts against the north side of Hardins Tower, where Jon used to sleep before being made the Old Bears steward.", 
     {"entities": [(35, 49, "LOCATION"), (87, 100, "LOCATION"), (108, 111, "PERSON"), (132, 142, "TITLE_PERSON")]}),
    ("Fingers of soot streaked the Lord Commanders Tower where the smoke had boiled from the windows.", 
     {"entities": [(25, 46, "LOCATION")]}),
    ("Mormont had moved to the Kings Tower after the fire, but Jon saw no lights there either.", 
     {"entities": [(0, 7, "PERSON"), (23, 34, "LOCATION"), (45, 48, "PERSON")]}),
    ("From the ground he could not tell if there were sentries walking the Wall seven hundred feet above, but he saw no one on the huge switchback stair that climbed the south face of the ice like some great wooden thunderbolt.", 
     {"entities": [(69, 73, "LOCATION")]}),
    ("There was smoke rising from the chimney of the armory, though; only a wisp, almost invisible against the grey northern sky, but it was enough.", 
     {"entities": []}),
    ("Jon dismounted and limped toward it.", 
     {"entities": [(0, 3, "PERSON")]}),
    ("Warmth poured out the open door like the hot breath of summer.", 
     {"entities": []}),
    ("Within, one-armed Donal Noye was working his bellows at the fire.", 
     {"entities": [(17, 27, "PERSON")]}),
    ("He looked up at the noise.", 
     {"entities": []}),
    ("Jon Snow? None else.", 
     {"entities": [(0, 8, "PERSON")]}),
    ("Despite fever, exhaustion, his leg, the Magnar, the old man, Ygritte, Mance, despite it all, Jon smiled.", 
     {"entities": [(35, 41, "TITLE"), (55, 61, "PERSON"), (63, 68, "PERSON"), (84, 87, "PERSON")]}),
    ("It was good to be back, good to see Noye with his big belly and pinned-up sleeve, his jaw bristling with black stubble.", 
     {"entities": [(29, 33, "PERSON")]}),
    ("The smith released his grip on the bellows.", 
     {"entities": [(4, 9, "TITLE")]}),
    ("Your face... He had almost forgotten about his face.", 
     {"entities": []}),
    ("A skinchanger tried to rip out my eye.", 
     {"entities": []}),
    ("Noye frowned.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Scarred or smooth, its a face I thought Id seen the last of.", 
     {"entities": []}),
    ("We heard youd gone over to Mance Raydar.", 
     {"entities": [(23, 34, "PERSON")]}),
    ("Jon grasped the door to stay upright.", 
     {"entities": [(0, 3, "PERSON")]}),
    ("Who told you that? Jarman Buckwell.", 
     {"entities": [(20, 34, "PERSON")]}),
# ]
# train_data = [
    ("Sire, Lord Walder said, forgive my Aegon the noise.", 
     {"entities": [(6, 16, "PERSON"), (31, 36, "PERSON")]}),
    ("He has less wits than a crannogman, and hes never met a king before.", 
     {"entities": []}),
    ("One of Stevrons boys. We call him Jinglebell.", 
     {"entities": [(8, 15, "PERSON"), (28, 38, "PERSON")]}),
    ("Ser Stevron mentioned him, my lord.", 
     {"entities": [(4, 11, "PERSON")]}),
    ("Robb smiled at the lackwit.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Well met, Aegon. Your father was a brave man.", 
     {"entities": [(10, 15, "PERSON")]}),
    ("Jinglebell jingled his bells.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("A thin line of spit ran from one corner of his mouth when he smiled.", 
     {"entities": []}),
    ("Save your royal breath. Youd do as well talking to a chamberpot.", 
     {"entities": []}),
    ("Lord Walder shifted his gaze to the others.", 
     {"entities": [(5, 15, "PERSON")]}),
    ("Well, Lady Catelyn, I see you have returned to us.", 
     {"entities": [(6, 19, "PERSON")]}),
    ("And young Ser Edmure, the victor of the Stone Mill.", 
     {"entities": [(11, 20, "PERSON"), (36, 46, "LOCATION")]}),
    ("Lord Tully now, Ill need to remember that.", 
     {"entities": [(5, 10, "TITLE")]}),
    ("Youre the fifth Lord Tully Ive known.", 
     {"entities": [(17, 22, "TITLE")]}),
    ("I outlived the other four, heh.", 
     {"entities": []}),
    ("Your brides about here somewhere.", 
     {"entities": []}),
    ("I suppose you want a look at her.", 
     {"entities": []}),
    ("I would, my lord.", 
     {"entities": []}),
    ("Then youll have it. But clothed.", 
     {"entities": []}),
    ("Shes a modest girl, and a maid.", 
     {"entities": []}),
    ("You wont see her naked till the bedding.", 
     {"entities": []}),
# ]
# train_data = [
    ("Areo Hotah said. Only what you did.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("It is for my prince to command, for Hotah to obey.", 
     {"entities": [(35, 40, "PERSON")]}),
    ("Arianne expected to be brought before her father's high seat beneath the dome of leaded glass in the Tower of the Sun.", 
     {"entities": [(0, 7, "PERSON"), (103, 120, "LOCATION")]}),
    ("Instead, Hotah delivered her to the Spear Tower, and the custody of her father's seneschal Ricasso and Ser Manfrey Martell, the castellan.", 
     {"entities": [(9, 14, "PERSON"), (34, 45, "LOCATION"), (79, 86, "PERSON"), (91, 109, "PERSON")]}),
    ("Princess, Ricasso said, you will forgive an old blind man if he does not make the climb with you.", 
     {"entities": [(10, 17, "PERSON")]}),
    ("Ser Manfrey shall escort you there, to await the prince's pleasure.", 
     {"entities": [(0, 11, "PERSON")]}),
    ("Arianne had been parted from Garin, Drey, and the others after capture,", 
     {"entities": [(0, 7, "PERSON"), (26, 31, "PERSON"), (33, 37, "PERSON")]}),
    ("They were taken to the Planky Town and will be conveyed by ship to Ghaston Grey,", 
     {"entities": [(20, 31, "LOCATION"), (57, 69, "LOCATION")]}),
    ("Ghaston Grey was a crumbling old castle perched on a rock in the Sea of Dorne,", 
     {"entities": [(0, 12, "LOCATION"), (58, 73, "LOCATION")]}),
    ("Does my father mean to kill them? Arianne could not believe it.", 
     {"entities": [(39, 46, "PERSON")]}),
    ("All they did they did for love for me.", 
     {"entities": []}),
    ("If my father must have blood, it should be mine.", 
     {"entities": []}),
    ("As you say, princess.", 
     {"entities": []}),
    ("The Spear Tower stood a hundred and a half feet high, and her cell was nearly at the top.", 
     {"entities": [(4, 15, "LOCATION")]}),
    ("Arianne eyed every door they passed, wondering if one of the Sand Snakes might be locked within.", 
     {"entities": [(0, 7, "PERSON"), (49, 59, "GROUP")]}),
    ("Her cell was large and airy, and did not lack for comforts.", 
     {"entities": []}),
    ("This high up, the views were splendid.", 
     {"entities": []}),
    ("One window opened to the east, so she could watch the sun rise above the sea.", 
     {"entities": []}),
    ("The other allowed her to look down upon the Tower of the Sun, and the Winding Walls and Threefold Gate beyond.", 
     {"entities": [(39, 56, "LOCATION"), (62, 75, "LOCATION"), (80, 94, "LOCATION")]}),
# ] #<<<<  WORK UNTIL EHRE
# train_data = [
    ("Griff told himself as he paced the deck of the Shy Maid.", 
     {"entities": [(0, 4, "PERSON"), (38, 47, "LOCATION")]}),
    ("Had they lost Haldon as they had Tyrion Lannister?", 
     {"entities": [(11, 17, "PERSON"), (32, 49, "PERSON")]}),
    ("Could the Volantenes have taken him?", 
     {"entities": [(4, 14, "GPE")]}),
    ("I should have sent Duck-field with him.", 
     {"entities": [(19, 29, "PERSON")]}),
    ("Haldon alone could not be trusted; he had proved that in Selhorys when he let the dwarf escape.", 
     {"entities": [(0, 6, "PERSON"), (51, 59, "LOCATION")]}),
    ("The Shy Maid was tied up in one of the meaner sections of the long, chaotic riverfront, between a listing poleboat that had not left the pier in years and the gaily painted mummers barge.", 
     {"entities": [(4, 13, "LOCATION")]}),
    ("The mummers were a loud and lively lot, always quoting speeches at each other and drunk more oft than not.", 
     {"entities": []}),
    ("The day was hot and sticky, as all the days had been since they left the Sorrows.", 
     {"entities": [(56, 64, "LOCATION")]}),
    ("A ferocious southern sun beat down upon the crowded riverfront of Volon Therys, but heat was the last and least of Griff's concerns.", 
     {"entities": [(69, 82, "LOCATION"), (97, 101, "PERSON")]}),
    ("The Golden Company was encamped three miles south of town, well north of where he had expected them,", 
     {"entities": [(4, 18, "ORGANIZATION")]}),
    ("and Triarch Malaquo had come north with five thousand foot and a thousand horse to cut them off from the delta road.", 
     {"entities": [(11, 27, "PERSON")]}),
    ("Daenerys Targaryen remained a world away, and Tyrion Lannister well, he could be most anywhere.", 
     {"entities": [(0, 16, "PERSON"), (28, 45, "PERSON")]}),
    ("If the gods were good, Lannisters severed head was halfway back to Kings Landing by now,", 
     {"entities": [(32, 48, "GPE")]}),
    ("but more like the dwarf was hale and whole and somewhere close, stinking drunk and plotting some new infamy.", 
     {"entities": []}),
    ("Where in the seven hells is Haldon?", 
     {"entities": [(22, 28, "PERSON")]}),
    ("Griff complained to Lady Lemore.", 
     {"entities": [(0, 4, "PERSON"), (17, 29, "PERSON")]}),
    ("How long should it take to buy three horses?", 
     {"entities": []}),
    ("She shrugged.", 
     {"entities": []}),
    ("My lord, wouldnt it be safer to leave the boy here aboard the boat?", 
     {"entities": []}),
    ("Safer, yes. Wiser, no.", 
     {"entities": []}),
    ("He is a man grown now, and this is the road that he was born to walk.", 
     {"entities": []}),
    ("Griff had no patience for this quibbling.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("He was sick of hiding, sick of waiting, sick of caution.", 
     {"entities": []}),
    ("I do not have time enough for caution.", 
     {"entities": []}),
    ("We have gone to great lengths to keep Prince Aegon hidden all these years, Lemore reminded him.", 
     {"entities": [(32, 38, "PERSON")]}),
    ("The time will come for him to wash his hair and declare himself, I know, but that time is not now.", 
     {"entities": []}),
    ("Not to a camp of sellswords.", 
     {"entities": []}),
    ("If Harry Strickland means him ill, hiding him on the Shy Maid will not protect him.", 
     {"entities": [(3, 17, "PERSON"), (42, 50, "LOCATION")]}),
    ("Strickland has ten thousand swords at his command.", 
     {"entities": [(0, 17, "PERSON")]}),
    ("We have Duck.", 
     {"entities": [(10, 14, "PERSON")]}),
    ("Aegon is all that could be wanted in a prince.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("They need to see that, Strickland and the rest.", 
     {"entities": [(0, 17, "PERSON")]}),
]
# train_data = [
#     ("When two of them finally came straggling back to the Wall, it had been as wights.", {"entities": [(34, 38, "LOCATION")]}),
#     ("Not for the first time, or the last, Jon Snow found himself wondering what had become of Benjen Stark.", {"entities": [(31, 39, "PERSON"), (44, 58, "PERSON")]}),
#     ("Dywen would lead one ranging, Black Jack Bulwer and Kedge Whit-eye the other two.", {"entities": [(0, 5, "PERSON"), (20, 38, "PERSON"), (43, 59, "PERSON")]}),
#     ("They at least were eager for the duty.", {"entities": []}),
#     ("Feels good to have a horse under me again, Dywen said at the gate, sucking on his wooden teeth.", {"entities": [(0, 5, "PERSON")]}),
#     ("No man in Castle Black knew the woods as well as Dywen did, the trees and streams, the plants that could be eaten, the ways of predator and prey.", {"entities": [(21, 34, "LOCATION"), (0, 5, "PERSON")]}),
#     ("Thorne is in better hands than he deserves.", {"entities": [(0, 6, "PERSON")]}),
#     ("Jon watched the riders go from atop the Wallthree parties, each of three men, each carrying a pair of ravens.", {"entities": [(0, 3, "PERSON"), (23, 27, "LOCATION")]}),
#     ("From on high their garrons looked no larger than ants, and Jon could not tell one ranger from another.", {"entities": [(14, 17, "PERSON")]}),
#     ("He knew them, though. Every name was graven on his heart.", {"entities": []}),
#     ("Eight good men, he thought, and one well, we shall see.", {"entities": []}),
#     ("When the last of the riders had disappeared into the trees, Jon Snow rode the winch cage down with Dolorous Edd.", {"entities": [(31, 39, "PERSON"), (48, 64, "PERSON")]}),
#     ("A few scattered snowflakes were falling as they made their slow descent, dancing on the gusty wind.", {"entities": []}),
#     ("Jon could have reached through the bars and caught it if he had wished.", {"entities": [(0, 3, "PERSON")]}),
#     ("I had a frightening dream last night, mlord, Dolorous Edd confessed.", {"entities": [(33, 48, "PERSON")]}),
#     ("You were my steward, fetching my food and cleaning up my leavings.", {"entities": []}),
#     ("I was lord commander, with never a moments peace.", {"entities": []}),
#     ("Jon did not smile.", {"entities": [(0, 3, "PERSON")]}),
#     ("Your nightmare, my life.", {"entities": []}),
#     ("Cotter Pykes galleys were reporting ever-increasing numbers of free folk along the wooded shores to the north and east of the Wall.", {"entities": [(0, 14, "PERSON"), (96, 100, "LOCATION")]}),
#     ("Camps had been seen, half-built rafts, even the hull of a broken cog that someone had begun repairing.", {"entities": []}),
#     ("The wildlings always vanished into the woods when seen, no doubt to reemerge as soon as Pykes ships had passed.", {"entities": [(4, 14, "RACE"), (22, 37, "PERSON")]}),
#     ("Meanwhile, Ser Denys Mallister was still seeing fires in the night north of the Gorge.", {"entities": [(16, 38, "PERSON"), (56, 62, "LOCATION")]}),
#     ("Both commanders were asking for more men.", {"entities": []}),
#     ("And where am I to get more men?", {"entities": []}),
#     ("Jon had sent ten of the Moles Town wildlings to each of them: green boys, old men, some wounded and infirm, but all capable of doing work of one sort or another.", {"entities": [(43, 56, "LOCATION"), (60, 71, "RACE")]}),
#     ("Far from being pleased, Pyke and Mallister had both written back to complain.", {"entities": [(60, 64, "PERSON"), (69, 80, "PERSON")]}),
#     ("When I asked for men, I had in mind men of the Nights Watch, trained and disciplined, whose loyalty I should never have reason to doubt, wrote Ser Denys.", {"entities": [(28, 42, "ORG"), (70, 88, "PERSON")]}),
#     ("Cotter Pyke was blunter.", {"entities": [(0, 13, "PERSON")]}),
#     ("I could hang them from the Wall as a warning to other wildlings to stay away, but I dont see any other use for them, Maester Harmune wrote for him.", {"entities": [(49, 53, "LOCATION"), (104, 120, "PERSON")]}),
#     ("I wouldnt trust such to clean my chamber pot, and ten is not enough.", {"entities": []}),
#     ("The iron cage moved downward at the end of its long chain, creaking and rattling, until it finally jerked to a halt a foot above the ground at the base of the Wall.", {"entities": [(33, 37, "LOCATION")]}),
#     ("Dolorous Edd pushed open the door and hopped down, his boots breaking the crust of the last snow.", {"entities": [(0, 16, "PERSON")]}),
#     ("Jon followed.", {"entities": [(0, 3, "PERSON")]}),
#     ("Outside the armory, Iron Emmett was still urging on his charges in the yard.", {"entities": [(25, 39, "PERSON")]}),
#     ("The song of steel on steel woke a hunger in Jon.", {"entities": [(27, 30, "PERSON")]}),
#     ("It reminded him of warmer, simpler days, when he had been a boy at Winterfell matching blades with Robb under the watchful eye of Ser Rodrik Cassel.", {"entities": [(56, 66, "LOCATION"), (70, 75, "PERSON"), (95, 114, "PERSON")]}),
#     ("Ser Rodrik too had fallen, slain by Theon Turncloak and his ironmen as hed tried to retake Winterfell.", {"entities": [(0, 13, "TITLE"), (41, 59, "PERSON"), (76, 85, "LOCATION")]}),
#     ("The great stronghold of House Stark was a scorched desolation.", {"entities": [(36, 45, "HOUSE")]}),
#     ("All my memories are poisoned.", {"entities": []}),
#     ("When Iron Emmett spied him, he raised a hand and combat ceased.", {"entities": [(6, 20, "PERSON")]}),
#     ("Lord Commander. How may we serve you?", {"entities": [("Lord Commander", "TITLE")]}),
#     ("With your three best.", {"entities": []}),
#     ("Emmett grinned. Arron. Emrick. Jace.", {"entities": [(0, 15, "PERSON"), (17, 23, "PERSON"), (25, 29, "PERSON")]}),
#     ("Horse and Hop-Robin fetched padding for the lord commander, along with a ringmail hauberk to go over it, and greaves, gorget, and halfhelm.", {"entities": [("lord commander", "TITLE")]}),
#     ("A black shield rimmed with iron for his left arm, a blunted longsword for his right hand.", {"entities": []}),
#     ("The sword gleamed silvery grey in the dawn light, almost new.", {"entities": []}),
#     ("One of the last to come from Donals forge.", {"entities": [("Donals", "PERSON")]}),
#     ("A pity he did not live long enough to put an edge on it.", {"entities": []}),
#     ("The blade was shorter than Longclaw but made of common steel, which made it heavier.", {"entities": []}),
#     ("It will serve.", {"entities": []}),
#     ("Jon turned to face his foes.", {"entities": [(0, 3, "PERSON")]}),
#     ("Come.", {"entities": []}),
#     ("Which one do you want first?", {"entities": []}),
#     ("asked Arron.", {"entities": [(5, 10, "PERSON")]}),
#     ("All three of you.", {"entities": []}),
#     ("At once.", {"entities": []}),
#     ("Three on one?", {"entities": []}),
#     ("Jace was incredulous.", {"entities": [(0, 4, "PERSON")]}),
#     ("That wouldnt be fair.", {"entities": []}),
#     ("He was one of Conwys latest bunch, a cobblers son from Fair Isle.", {"entities": [(34, 40, "PERSON"), (45, 55, "LOCATION")]}),
# # ]
# # train_data = [
# #     ("Ramsay Bolton had returned and would want his Reek on hand to serve him.", {"entities": [(0, 14, "PERSON"), (44, 48, "PERSON")]}),
# #     ("Outside, beneath a cold autumnal sky, the hunters were pouring through the gates.", {"entities": [("hunters", "OBJECT")]}),
# #     ("Ben Bones led the way, with the girls baying and barking all around him.", {"entities": [("Ben Bones", "PERSON"), ("girls", "OBJECT")]}),
# #     ("Behind came Skinner, Sour Alyn, and Damon Dance-for-Me with his long greased whip,", {"entities": [("Skinner", "PERSON"), ("Sour Alyn", "PERSON"), ("Damon Dance-for-Me", "PERSON")]}),
# #     ("then the Walders riding the grey colts Lady Dustin had given them.", {"entities": [("Walders", "PERSON"), ("Lady Dustin", "PERSON")]}),
# #     ("His lordship himself rode Blood, a red stallion with a temper to match his own.", {"entities": [("lordship", "TITLE"), ("Blood", "OBJECT")]}),
# #     ("He was laughing. That could be very good or very bad, Reek knew.", {"entities": [("Reek", "PERSON")]}),
# #     ("The dogs were on him before he could puzzle out which, drawn to his scent.", {"entities": [("dogs", "OBJECT")]}),
# #     ("The dogs were fond of Reek; he slept with them oft as not, and sometimes Ben Bones let him share their supper.", {"entities": [("Reek", "PERSON"), ("Ben Bones", "PERSON")]}),
# #     ("The pack raced across the flagstones barking, circling him, jumping up to lick his filthy face, nipping at his legs.", {"entities": [("pack", "OBJECT")]}),
# #     ("Helicent caught his left hand between her teeth and worried it so fiercely Reek feared he might lose two more fingers.", {"entities": [("Helicent", "PERSON"), ("Reek", "PERSON")]}),
# #     ("Red Jeyne slammed into his chest and knocked him off his feet.", {"entities": [("Red Jeyne", "PERSON")]}),
# #     ("She was lean, hard muscle, where Reek was loose, grey skin and brittle bones, a white-haired starveling.", {"entities": [("Reek", "PERSON")]}),
# #     ("The riders were dismounting by the time he pushed Red Jeyne off and struggled to his knees.", {"entities": [("riders", "OBJECT"), ("Red Jeyne", "PERSON")]}),
# #     ("Two dozen horsemen had gone out and two dozen had returned, which meant the search had been a failure.", {"entities": [("horsemen", "OBJECT")]}),
# #     ("That was bad. Ramsay did not like the taste of failure.", {"entities": [("Ramsay", "PERSON")]}),
# #     ("He will want to hurt someone.", {"entities": [("someone", "PERSON")]}),
# #     ("Of late, his lord had been forced to restrain himself, for Barrowton was full of men House Bolton needed, and Ramsay knew to be careful around the Dustins and Ryswells and his fellow lordlings.", {"entities": [("Barrowton", "LOCATION"), ("House Bolton", "ORG"), ("Dustins", "PERSON"), ("Ryswells", "PERSON")]}),
# #     ("With them he was always courteous and smiling.", {"entities": []}),
# #     ("What he was behind closed doors was something else.", {"entities": []}),
# #     ("Ramsay Bolton was attired as befit the lord of the Hornwood and heir to the Dreadfort.", {"entities": [("Ramsay Bolton", "PERSON"), ("lord", "TITLE"), ("Hornwood", "LOCATION"), ("Dreadfort", "LOCATION")]})
# # ]
train_data = [
    ("These mountains were the domain of House Arryn, and the late Hands widow was a Tully, Catelyn Starks sister...", 
     {"entities": [(32, 43, "HOUSE"), (71, 76, "HOUSE"), (78, 92, "PERSON")]}),
    ("...and no friend to the Lannisters.", 
     {"entities": [(21, 31, "HOUSE")]}),
    ("Tyrion had known the Lady Lysa slightly during her years at Kings Landing, and did not look forward to renewing the acquaintance.", 
     {"entities": [(0, 6, "PERSON"), (21, 31, "TITLE"), (32, 36, "PERSON"), (61, 74, "LOCATION")]}),
    ("His captors were clustered around a stream a short ways down the high road.", 
     {"entities": []}),
    ("The horses had drunk their fill of the icy cold water, and were grazing on clumps of brown grass that grew from clefts in the rock.", 
     {"entities": []}),
    ("Jyck and Morrec huddled close, sullen and miserable.", 
     {"entities": [(0, 4, "PERSON"), (9, 15, "PERSON")]}),
    ("Mohor stood over them, leaning on his spear and wearing a rounded iron cap that made him look as if he had a bowl on his head.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Nearby, Marillion the singer sat oiling his woodharp, complaining of what the damp was doing to his strings.", 
     {"entities": [(9, 18, "PERSON"), (23, 29, "TITLE"), (40, 48, "OBJECT")]}),
    ("We must have some rest, my lady, the hedge knight Ser Willis Wode was saying to Catelyn Stark as Tyrion approached.", 
     {"entities": [(34, 41, "TITLE"), (42, 56, "PERSON"), (60, 72, "PERSON"), (76, 82, "PERSON")]}),
    ("He was Lady Whents man, stiff-necked and stolid, and the first to rise to aid Catelyn Stark back at the inn.", 
     {"entities": [(7, 17, "TITLE"), (18, 23, "HOUSE"), (51, 63, "PERSON")]}),
    ("Ser Willis speaks truly, my lady, Ser Rodrik said.", 
     {"entities": [(0, 9, "TITLE"), (10, 16, "PERSON"), (38, 48, "TITLE"), (49, 55, "PERSON")]}),
    ("This is the third horse we have lost.", 
     {"entities": []}),
    ("We will lose more than horses if were overtaken by the Lannisters, she reminded them.", 
     {"entities": [(54, 64, "HOUSE")]}),
    ("Her face was windburnt and gaunt, but it had lost none of its determination.", 
     {"entities": []}),
    ("Small chance of that here, Tyrion put in.", 
     {"entities": [(26, 32, "PERSON")]}),
    ("The lady did not ask your views, dwarf, snapped Kurleket, a great fat oaf with short- cropped hair and a pigs face.", 
     {"entities": [(46, 54, "PERSON")]}),
    ("He was one of the Brackens, a man-at-arms in the service of Lord Jonos.", 
     {"entities": [(18, 26, "HOUSE"), (52, 57, "TITLE"), (58, 63, "PERSON")]}),
    ("Tyrion had made a special effort to learn all their names, so he might thank them later for their tender treatment of him.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("A Lannister always paid his debts.", 
     {"entities": [(2, 11, "HOUSE")]}),
    ("Kurleket would learn that someday, as would his friends Lharys and Mohor, and the good Ser Willis, and the sellswords Bronn and Chiggen.", 
     {"entities": [(0, 8, "PERSON"), (38, 44, "PERSON"), (49, 54, "PERSON"), (70, 80, "TITLE"), (81, 87, "PERSON"), (105, 110, "PERSON"), (115, 122, "PERSON")]}),
# ]
# train_data = [
    ("Arya stood rooted to the spot.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Nothing bads happened to Jon, has it? she asked Yoren.", 
     {"entities": [(25, 28, "PERSON"), (43, 48, "PERSON")]}),
    ("Or Uncle Benjen?", 
     {"entities": [(9, 15, "PERSON")]}),
    ("Well, as to Stark, I cant say.", 
     {"entities": [(10, 15, "HOUSE")]}),
    ("The Snow boy was well enough when I left the Wall.", 
     {"entities": [(4, 8, "HOUSE"), (41, 49, "LOCATION")]}),
    ("Its not them as concerns me.", 
     {"entities": []}),
    ("Desmond took her hand.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Come along, milady. You heard your lord father.", 
     {"entities": [(13, 19, "TITLE")]}),
    ("Arya had no choice but to go with him, wishing it had been Fat Tom.", 
     {"entities": [(0, 4, "PERSON"), (46, 53, "PERSON")]}),
    ("With Tom, she might have been able to linger at the door on some excuse and hear what Yoren was saying, but Desmond was too single-minded to trick.", 
     {"entities": [(5, 8, "PERSON"), (75, 80, "PERSON"), (86, 93, "PERSON")]}),
    ("How many guards does my father have? she asked him as they descended to her bedchamber.", 
     {"entities": []}),
    ("Here at Kings Landing? Fifty.", 
     {"entities": [(9, 22, "LOCATION")]}),
    ("You wouldnt let anyone kill him, would you? she asked.", 
     {"entities": []}),
    ("Desmond laughed.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("No fear on that count, little lady. Lord Eddards guarded night and day.", 
     {"entities": [(32, 36, "TITLE"), (37, 43, "PERSON")]}),
    ("Hell come to no harm.", 
     {"entities": []}),
    ("The Lannisters have more than fifty men, Arya pointed out.", 
     {"entities": [(4, 14, "HOUSE"), (41, 45, "PERSON")]}),
    ("So they do, but every northerner is worth ten of these southron swords, so you can sleep easy.", 
     {"entities": []}),
    ("What if a wizard was sent to kill him?", 
     {"entities": [(12, 18, "TITLE")]}),
    ("Well, as to that, Desmond replied, drawing his longsword, wizards die the same as other men, once you cut their heads off.", 
     {"entities": [(14, 21, "PERSON"), (40, 49, "OBJECT")]}),
# ]
# train_data = [
    ("Ser Jorah Mormont said, The Western Market will have food more to your taste, Your Grace.", 
     {"entities": [(0, 15, "PERSON"), (21, 37, "LOCATION"), (61, 71, "TITLE")]}),
    ("The traders from the Free Cities come there to sell their wares.", 
     {"entities": [(21, 32, "LOCATION")]}),
    ("The khal will honor his promise in his own time.", 
     {"entities": [(4, 8, "TITLE")]}),
    ("He had better, Viserys said grimly.", 
     {"entities": [(13, 20, "PERSON")]}),
    ("I was promised a crown, and I mean to have it.", 
     {"entities": [(19, 24, "OBJECT")]}),
    ("The dragon is not mocked.", 
     {"entities": [(4, 10, "PSEUDONYM")]}),
    ("Spying an obscene likeness of a woman with six breasts and a ferrets head, he rode off to inspect it more closely.", 
     {"entities": []}),
    ("Dany was relieved, yet no less anxious.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("I pray that my sun-and-stars will not keep him waiting too long, she told Ser Jorah when her brother was out of earshot.", 
     {"entities": [(44, 49, "TITLE"), (60, 75, "PERSON")]}),
    ("The knight looked after Viserys doubtfully.", 
     {"entities": [(18, 25, "PERSON")]}),
    ("Your brother should have bided his time in Pentos.", 
     {"entities": [(38, 44, "LOCATION")]}),
    ("There is no place for him in a khalasar.", 
     {"entities": [(30, 38, "LOCATION")]}),
    ("Illyrio tried to warn him.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("He will go as soon as he has his ten thousand.", 
     {"entities": []}),
    ("My lord husband promised a golden crown.", 
     {"entities": [(3, 7, "TITLE"), (27, 33, "OBJECT")]}),
    ("Ser Jorah grunted.", 
     {"entities": [(0, 9, "PERSON")]}),
    ("Yes, Khaleesi, but... the Dothraki look on these things differently than we do in the west.", 
     {"entities": [(5, 13, "TITLE"), (20, 28, "RACE")]}),
    ("I have told him as much, as Illyrio told him, but your brother does not listen.", 
     {"entities": [(27, 34, "PERSON")]}),
    ("The horselords are no traders.", 
     {"entities": [(4, 14, "RACE")]}),
    ("Viserys thinks he sold you, and now he wants his price.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Yet Khal Drogo would say he had you as a gift.", 
     {"entities": [(4, 14, "PERSON")]}),
    ("He will give Viserys a gift in return, yes... in his own time.", 
     {"entities": [(13, 20, "PERSON")]}),
    ("You do not demand a gift, not of a khal.", 
     {"entities": [(30, 34, "TITLE")]}),
    ("You do not demand anything of a khal.", 
     {"entities": [(30, 34, "TITLE")]}),
    ("It is not right to make him wait.", 
     {"entities": []}),
    ("Dany did not know why she was defending her brother, yet she was.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Viserys says he could sweep the Seven Kingdoms with ten thousand Dothraki screamers.", 
     {"entities": [(0, 7, "PERSON"), (26, 40, "LOCATION"), (55, 63, "RACE")]}),
    ("Ser Jorah snorted.", 
     {"entities": [(0, 9, "PERSON")]}),
    ("Viserys could not sweep a stable with ten thousand brooms.", 
     {"entities": [(0, 7, "PERSON")]}),
    ("Dany could not pretend to surprise at the disdain in his tone.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("What... what if it were not Viserys? she asked.", 
     {"entities": [(26, 33, "PERSON")]}),
    ("If it were someone else who led them? Someone stronger?", 
     {"entities": []}),
    ("Could the Dothraki truly conquer the Seven Kingdoms?", 
     {"entities": [(10, 18, "RACE"), (39, 53, "LOCATION")]}),
# ] # <<<< WORK UNTIL HERE
# train_data = [
    ("The master of the Kings Galley White Hart plots to slip anchor three days hence to offer his sword and ship to Lord Stannis.", 
     {"entities": [(16, 29, "TITLE"), (30, 40, "OBJECT"), (74, 85, "PERSON")]}),
    ("Tyrion sighed.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("I suppose we must make some sort of bloody lesson out of the man?", 
     {"entities": []}),
    ("Ser Jacelyn could arrange for him to vanish, but a trial before the king would help assure the continued loyalty of the other captains.", 
     {"entities": [(0, 10, "PERSON"), (40, 44, "TITLE")]}),
    ("And keep my royal nephew occupied as well.", 
     {"entities": []}),
    ("As you say. Put him down for a dose of Joffreys justice.", 
     {"entities": [(36, 44, "PERSON")]}),
    ("Varys made a mark on the parchment.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Ser Horas and Ser Hobber Redwyne have bribed a guard to let them out of a postern gate, the night after next.", 
     {"entities": [(0, 9, "PERSON"), (14, 26, "PERSON")]}),
    ("Arrangements have been made for them to sail on the Pentoshi galley Moonrunner, disguised as oarsmen.", 
     {"entities": [(46, 54, "LOCATION"), (62, 72, "OBJECT")]}),
    ("Can we keep them on those oars for a few years, see how they fancy it?", 
     {"entities": []}),
    ("He smiled.", 
     {"entities": []}),
    ("No, my sister would be distraught to lose such treasured guests.", 
     {"entities": []}),
    ("Inform Ser Jacelyn. Seize the man they bribed and explain what an honor it is to serve as a brother of the Nights Watch.", 
     {"entities": [(7, 17, "PERSON"), (88, 100, "ORGANIZATION")]}),
    ("And have men posted around the Moonrunner, in case the Redwynes find a second guard short of coin.", 
     {"entities": [(28, 38, "OBJECT"), (48, 56, "FAMILY")]}),
    ("As you will.", 
     {"entities": []}),
    ("Another mark on the parchment.", 
     {"entities": []}),
    ("Your man Timett slew a winesellers son this evening, at a gambling den on the Street of Silver.", 
     {"entities": [(9, 15, "PERSON"), (67, 84, "LOCATION")]}),
    ("He accused him of cheating at tiles.", 
     {"entities": []}),
    ("Was it true?", 
     {"entities": []}),
    ("Oh, beyond a doubt.", 
     {"entities": []}),
    ("Then the honest men of the city owe Timett a debt of gratitude.", 
     {"entities": [(33, 39, "PERSON")]}),
    ("I shall see that he has the kings thanks.", 
     {"entities": [(28, 33, "TITLE")]}),
    ("The eunuch gave a nervous giggle and made another mark.", 
     {"entities": []}),
    ("We also have a sudden plague of holy men.", 
     {"entities": []}),
    ("The comet has brought forth all manner of queer priests, preachers, and prophets, it would seem.", 
     {"entities": []}),
    ("They beg in the winesinks and pot-shops and foretell doom and destruction to anyone who stops to listen.", 
     {"entities": []}),
    ("Tyrion shrugged.", 
     {"entities": [(0, 6, "PERSON")]}),
    ("We are close on the three hundredth year since Aegons Landing, I suppose it is only to be expected.", 
     {"entities": [(45, 58, "EVENT")]}),
    ("Let them rant.", 
     {"entities": []}),
    ("They are spreading fear, my lord.", 
     {"entities": []}),
    ("I thought that was your job.", 
     {"entities": []}),
    ("Varys covered his mouth with his hand.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("You are very cruel to say so.", 
     {"entities": []}),
    ("One last matter.", 
     {"entities": []}),
    ("Lady Tanda gave a small supper last night.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("I have the menu and the guest list for your inspection.", 
     {"entities": []}),
    ("When the wine was poured, Lord Gyles rose to lift a cup to the king, and Ser Balon Swann was heard to remark, Well need three cups for that.", 
     {"entities": [(31, 41, "PERSON"), (61, 77, "PERSON")]}),
# ]
# train_data = [
    ("Your eunuch must have told you, there is small love for the Lannisters in Kings Landing.", 
     {"entities": [(33, 43, "FAMILY"), (47, 59, "LOCATION")]}),
    ("Many still remember how your lord father sacked the city, when Aerys opened the gates to him.", 
     {"entities": [(63, 68, "PERSON")]}),
    ("They whisper that the gods are punishing us for the sins of your Housefor your brothers murder of King Aerys, for the butchery of Rhaegars children, for the execution of Eddard Stark and the savagery of Joffreys justice.", 
     {"entities": [(50, 68, "TITLE"), (90, 97, "PERSON"), (128, 140, "PERSON"), (159, 167, "PERSON")]}),
    ("Some talk openly of how much better things were when Robert was king, and hint that times would be better again with Stannis on the throne.", 
     {"entities": [(45, 51, "PERSON"), (95, 102, "PERSON")]}),
    ("In pot-shops and winesinks and brothels, you hear these thingsand in the barracks and guardhalls as well, I fear.", 
     {"entities": []}),
    ("They hate my family, is that what you are telling me?", 
     {"entities": []}),
    ("Aye... and will turn on them, if the chance comes.", 
     {"entities": []}),
    ("Me as well? Ask your eunuch.", 
     {"entities": []}),
    ("Im asking you.", 
     {"entities": []}),
    ("Bywaters deep-set eyes met the dwarfs mismatched ones, and did not blink.", 
     {"entities": [(0, 8, "PERSON")]}),
    ("You most of all, my lord.", 
     {"entities": []}),
    ("Most of all? The injustice was like to choke him.", 
     {"entities": []}),
    ("It was Joffrey who told them to eat their dead, Joffrey who set his dog on them.", 
     {"entities": [(8, 15, "PERSON"), (45, 52, "PERSON")]}),
    ("How could they blame me?", 
     {"entities": []}),
    ("His Grace is but a boy.", 
     {"entities": [(4, 9, "TITLE")]}),
    ("In the streets, it is said that he has evil councilors.", 
     {"entities": []}),
    ("The queen has never been known as a friend to the commons, nor is Lord Varys called the Spider out of love...", 
     {"entities": [(4, 9, "TITLE"), (56, 66, "TITLE"), (67, 72, "PERSON")]}),
    ("but it is you they blame most.", 
     {"entities": []}),
    ("Your sister and the eunuch were here when times were better under King Robert, but you were not.", 
     {"entities": [(70, 75, "TITLE"), (76, 82, "PERSON")]}),
    ("They say that youve filled the city with swaggering sellswords and unwashed savages, brutes who take what they want and follow no laws but their own.", 
     {"entities": []}),
    ("They say you exiled Janos Slynt because you found him too bluff and honest for your liking.", 
     {"entities": [(18, 29, "PERSON")]}),
    ("They say you threw wise and gentle Pycelle into the dungeons when he dared raise his voice against you.", 
     {"entities": [(28, 35, "PERSON")]}),
    ("Some even claim that you mean to seize the Iron Throne for your own.", 
     {"entities": [(34, 45, "OBJECT")]}),
# ]
# train_data = [
    ("Ser Rodrik had needed every man of fighting age he could lay his hands on, so Winterfell had been left with only a token garrison.", 
     {"entities": [(4, 10, "PERSON"), (61, 71, "LOCATION")]}),
    ("The rest had left eight days past, six hundred men from Winterfell and the nearest holdfasts.", 
     {"entities": [(51, 61, "LOCATION")]}),
    ("Cley Cerwyn was bringing three hundred more to join them on the march, and Maester Luwin had sent ravens before them, summoning levies from White Harbor and the barrowlands and even the deep places inside the wolfswood.", 
     {"entities": [(0, 11, "PERSON"), (55, 68, "TITLE"), (69, 74, "PERSON"), (108, 120, "LOCATION"), (129, 140, "LOCATION"), (169, 178, "LOCATION")]}),
    ("Torrhens Square was under attack by some monstrous war chief named Dagmer Cleftjaw.", 
     {"entities": [(0, 15, "LOCATION"), (62, 77, "PERSON")]}),
    ("Old Nan said he couldnt be killed, that once a foe had cut his head in two with an axe, but Dagmer was so fierce hed just pushed the two halves back together and held them until they healed up.", 
     {"entities": [(0, 7, "PERSON"), (77, 83, "PERSON")]}),
    ("Could Dagmer have won?", 
     {"entities": [(6, 12, "PERSON")]}),
    ("Torrhens Square was many days from Winterfell, yet still...", 
     {"entities": [(0, 15, "LOCATION"), (35, 45, "LOCATION")]}),
    ("Bran pulled himself from the bed, moving bar to bar until he reached the windows.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("His fingers fumbled a little as he swung back the shutters.", 
     {"entities": []}),
    ("The yard was empty, and all the windows he could see were black.", 
     {"entities": []}),
    ("Winterfell slept.", 
     {"entities": [(0, 10, "LOCATION")]}),
    ("Hodor! he shouted down, as loud as he could.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Hodor would be asleep above the stables, but maybe if he yelled loud enough hed hear, or somebody would.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Hodor, come fast! Osha! Meera, Jojen, anyone!", 
     {"entities": [(0, 5, "PERSON"), (18, 22, "PERSON"), (24, 29, "PERSON"), (31, 36, "PERSON")]}),
    ("Bran cupped his hands around his mouth.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("HOOOOODOOOOOR!", 
     {"entities": []}),
    ("But when the door crashed open behind him, the man who stepped through was no one Bran knew.", 
     {"entities": [(68, 72, "PERSON")]}),
    ("He wore a leather jerkin sewn with overlapping iron disks, and carried a dirk in one hand and an axe strapped to his back.", 
     {"entities": []}),
    ("What do you want? Bran demanded, afraid.", 
     {"entities": [(16, 20, "PERSON")]}),
    ("This is my room. You get out of here.", 
     {"entities": []}),
    ("Theon Greyjoy followed him into the bedchamber.", 
     {"entities": [(0, 13, "PERSON")]}),
    ("Were not here to harm you, Bran.", 
     {"entities": [(27, 31, "PERSON")]}),
    ("Theon? Bran felt dizzy with relief.", 
     {"entities": [(0, 5, "PERSON"), (7, 11, "PERSON")]}),
    ("Did Robb send you? Is he here too?", 
     {"entities": [(4, 8, "PERSON")]}),
    ("Robbs far away. He cant help you now.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("Help me? He was confused.", 
     {"entities": []}),
    ("Dont scare me, Theon.", 
     {"entities": [(17, 22, "PERSON")]}),
    ("Im Prince Theon now.", 
     {"entities": [(4, 16, "TITLE_PERSON")]}),
    ("Were both princes, Bran.", 
     {"entities": [(19, 23, "PERSON")]}),
    ("Who would have dreamed it? But Ive taken your castle, my prince.", 
     {"entities": []}),
    ("Winterfell? Bran shook his head.", 
     {"entities": [(0, 10, "LOCATION"), (12, 16, "PERSON")]}),
    ("No, you couldnt. Leave us, Werlag.", 
     {"entities": [(27, 33, "PERSON")]}),
# ]
# train_data = [
    ("Castle Black seemed as much a ruin as Greyguard.", 
     {"entities": [(0, 12, "LOCATION"), (35, 44, "LOCATION")]}),
    ("Brown brittle weeds grew between cracks in the stones of the courtyards.", 
     {"entities": []}),
    ("Old snow covered the roof of the Flint Barracks and lay in drifts against the north side of Hardins Tower, where Jon used to sleep before being made the Old Bears steward.", 
     {"entities": [(35, 49, "LOCATION"), (87, 100, "LOCATION"), (108, 111, "PERSON"), (132, 142, "TITLE_PERSON")]}),
    ("Fingers of soot streaked the Lord Commanders Tower where the smoke had boiled from the windows.", 
     {"entities": [(25, 46, "LOCATION")]}),
    ("Mormont had moved to the Kings Tower after the fire, but Jon saw no lights there either.", 
     {"entities": [(0, 7, "PERSON"), (23, 34, "LOCATION"), (45, 48, "PERSON")]}),
    ("From the ground he could not tell if there were sentries walking the Wall seven hundred feet above, but he saw no one on the huge switchback stair that climbed the south face of the ice like some great wooden thunderbolt.", 
     {"entities": [(69, 73, "LOCATION")]}),
    ("There was smoke rising from the chimney of the armory, though; only a wisp, almost invisible against the grey northern sky, but it was enough.", 
     {"entities": []}),
    ("Jon dismounted and limped toward it.", 
     {"entities": [(0, 3, "PERSON")]}),
    ("Warmth poured out the open door like the hot breath of summer.", 
     {"entities": []}),
    ("Within, one-armed Donal Noye was working his bellows at the fire.", 
     {"entities": [(17, 27, "PERSON")]}),
    ("He looked up at the noise.", 
     {"entities": []}),
    ("Jon Snow? None else.", 
     {"entities": [(0, 8, "PERSON")]}),
    ("Despite fever, exhaustion, his leg, the Magnar, the old man, Ygritte, Mance, despite it all, Jon smiled.", 
     {"entities": [(35, 41, "TITLE"), (55, 61, "PERSON"), (63, 68, "PERSON"), (84, 87, "PERSON")]}),
    ("It was good to be back, good to see Noye with his big belly and pinned-up sleeve, his jaw bristling with black stubble.", 
     {"entities": [(29, 33, "PERSON")]}),
    ("The smith released his grip on the bellows.", 
     {"entities": [(4, 9, "TITLE")]}),
    ("Your face... He had almost forgotten about his face.", 
     {"entities": []}),
    ("A skinchanger tried to rip out my eye.", 
     {"entities": []}),
    ("Noye frowned.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Scarred or smooth, its a face I thought Id seen the last of.", 
     {"entities": []}),
    ("We heard youd gone over to Mance Raydar.", 
     {"entities": [(23, 34, "PERSON")]}),
    ("Jon grasped the door to stay upright.", 
     {"entities": [(0, 3, "PERSON")]}),
    ("Who told you that? Jarman Buckwell.", 
     {"entities": [(20, 34, "PERSON")]}),
# ]
# train_data = [
    ("Sire, Lord Walder said, forgive my Aegon the noise.", 
     {"entities": [(6, 16, "PERSON"), (31, 36, "PERSON")]}),
    ("He has less wits than a crannogman, and hes never met a king before.", 
     {"entities": []}),
    ("One of Stevrons boys. We call him Jinglebell.", 
     {"entities": [(8, 15, "PERSON"), (28, 38, "PERSON")]}),
    ("Ser Stevron mentioned him, my lord.", 
     {"entities": [(4, 11, "PERSON")]}),
    ("Robb smiled at the lackwit.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("Well met, Aegon. Your father was a brave man.", 
     {"entities": [(10, 15, "PERSON")]}),
    ("Jinglebell jingled his bells.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("A thin line of spit ran from one corner of his mouth when he smiled.", 
     {"entities": []}),
    ("Save your royal breath. Youd do as well talking to a chamberpot.", 
     {"entities": []}),
    ("Lord Walder shifted his gaze to the others.", 
     {"entities": [(5, 15, "PERSON")]}),
    ("Well, Lady Catelyn, I see you have returned to us.", 
     {"entities": [(6, 19, "PERSON")]}),
    ("And young Ser Edmure, the victor of the Stone Mill.", 
     {"entities": [(11, 20, "PERSON"), (36, 46, "LOCATION")]}),
    ("Lord Tully now, Ill need to remember that.", 
     {"entities": [(5, 10, "TITLE")]}),
    ("Youre the fifth Lord Tully Ive known.", 
     {"entities": [(17, 22, "TITLE")]}),
    ("I outlived the other four, heh.", 
     {"entities": []}),
    ("Your brides about here somewhere.", 
     {"entities": []}),
    ("I suppose you want a look at her.", 
     {"entities": []}),
    ("I would, my lord.", 
     {"entities": []}),
    ("Then youll have it. But clothed.", 
     {"entities": []}),
    ("Shes a modest girl, and a maid.", 
     {"entities": []}),
    ("You wont see her naked till the bedding.", 
     {"entities": []}),
# ]
# train_data = [
    ("Areo Hotah said. Only what you did.", 
     {"entities": [(0, 10, "PERSON")]}),
    ("It is for my prince to command, for Hotah to obey.", 
     {"entities": [(35, 40, "PERSON")]}),
    ("Arianne expected to be brought before her father's high seat beneath the dome of leaded glass in the Tower of the Sun.", 
     {"entities": [(0, 7, "PERSON"), (103, 120, "LOCATION")]}),
    ("Instead, Hotah delivered her to the Spear Tower, and the custody of her father's seneschal Ricasso and Ser Manfrey Martell, the castellan.", 
     {"entities": [(9, 14, "PERSON"), (34, 45, "LOCATION"), (79, 86, "PERSON"), (91, 109, "PERSON")]}),
    ("Princess, Ricasso said, you will forgive an old blind man if he does not make the climb with you.", 
     {"entities": [(10, 17, "PERSON")]}),
    ("Ser Manfrey shall escort you there, to await the prince's pleasure.", 
     {"entities": [(0, 11, "PERSON")]}),
    ("Arianne had been parted from Garin, Drey, and the others after capture,", 
     {"entities": [(0, 7, "PERSON"), (26, 31, "PERSON"), (33, 37, "PERSON")]}),
    ("They were taken to the Planky Town and will be conveyed by ship to Ghaston Grey,", 
     {"entities": [(20, 31, "LOCATION"), (57, 69, "LOCATION")]}),
    ("Ghaston Grey was a crumbling old castle perched on a rock in the Sea of Dorne,", 
     {"entities": [(0, 12, "LOCATION"), (58, 73, "LOCATION")]}),
    ("Does my father mean to kill them? Arianne could not believe it.", 
     {"entities": [(39, 46, "PERSON")]}),
    ("All they did they did for love for me.", 
     {"entities": []}),
    ("If my father must have blood, it should be mine.", 
     {"entities": []}),
    ("As you say, princess.", 
     {"entities": []}),
    ("The Spear Tower stood a hundred and a half feet high, and her cell was nearly at the top.", 
     {"entities": [(4, 15, "LOCATION")]}),
    ("Arianne eyed every door they passed, wondering if one of the Sand Snakes might be locked within.", 
     {"entities": [(0, 7, "PERSON"), (49, 59, "GROUP")]}),
    ("Her cell was large and airy, and did not lack for comforts.", 
     {"entities": []}),
    ("This high up, the views were splendid.", 
     {"entities": []}),
    ("One window opened to the east, so she could watch the sun rise above the sea.", 
     {"entities": []}),
    ("The other allowed her to look down upon the Tower of the Sun, and the Winding Walls and Threefold Gate beyond.", 
     {"entities": [(39, 56, "LOCATION"), (62, 75, "LOCATION"), (80, 94, "LOCATION")]}),
# ] #<<<<  WORK UNTIL EHRE
# train_data = [
    ("Griff told himself as he paced the deck of the Shy Maid.", 
     {"entities": [(0, 4, "PERSON"), (38, 47, "LOCATION")]}),
    ("Had they lost Haldon as they had Tyrion Lannister?", 
     {"entities": [(11, 17, "PERSON"), (32, 49, "PERSON")]}),
    ("Could the Volantenes have taken him?", 
     {"entities": [(4, 14, "GPE")]}),
    ("I should have sent Duck-field with him.", 
     {"entities": [(19, 29, "PERSON")]}),
    ("Haldon alone could not be trusted; he had proved that in Selhorys when he let the dwarf escape.", 
     {"entities": [(0, 6, "PERSON"), (51, 59, "LOCATION")]}),
    ("The Shy Maid was tied up in one of the meaner sections of the long, chaotic riverfront, between a listing poleboat that had not left the pier in years and the gaily painted mummers barge.", 
     {"entities": [(4, 13, "LOCATION")]}),
    ("The mummers were a loud and lively lot, always quoting speeches at each other and drunk more oft than not.", 
     {"entities": []}),
    ("The day was hot and sticky, as all the days had been since they left the Sorrows.", 
     {"entities": [(56, 64, "LOCATION")]}),
    ("A ferocious southern sun beat down upon the crowded riverfront of Volon Therys, but heat was the last and least of Griff's concerns.", 
     {"entities": [(69, 82, "LOCATION"), (97, 101, "PERSON")]}),
    ("The Golden Company was encamped three miles south of town, well north of where he had expected them,", 
     {"entities": [(4, 18, "ORGANIZATION")]}),
    ("and Triarch Malaquo had come north with five thousand foot and a thousand horse to cut them off from the delta road.", 
     {"entities": [(11, 27, "PERSON")]}),
    ("Daenerys Targaryen remained a world away, and Tyrion Lannister well, he could be most anywhere.", 
     {"entities": [(0, 16, "PERSON"), (28, 45, "PERSON")]}),
    ("If the gods were good, Lannisters severed head was halfway back to Kings Landing by now,", 
     {"entities": [(32, 48, "GPE")]}),
    ("but more like the dwarf was hale and whole and somewhere close, stinking drunk and plotting some new infamy.", 
     {"entities": []}),
    ("Where in the seven hells is Haldon?", 
     {"entities": [(22, 28, "PERSON")]}),
    ("Griff complained to Lady Lemore.", 
     {"entities": [(0, 4, "PERSON"), (17, 29, "PERSON")]}),
    ("How long should it take to buy three horses?", 
     {"entities": []}),
    ("She shrugged.", 
     {"entities": []}),
    ("My lord, wouldnt it be safer to leave the boy here aboard the boat?", 
     {"entities": []}),
    ("Safer, yes. Wiser, no.", 
     {"entities": []}),
    ("He is a man grown now, and this is the road that he was born to walk.", 
     {"entities": []}),
    ("Griff had no patience for this quibbling.", 
     {"entities": [(0, 4, "PERSON")]}),
    ("He was sick of hiding, sick of waiting, sick of caution.", 
     {"entities": []}),
    ("I do not have time enough for caution.", 
     {"entities": []}),
    ("We have gone to great lengths to keep Prince Aegon hidden all these years, Lemore reminded him.", 
     {"entities": [(32, 38, "PERSON")]}),
    ("The time will come for him to wash his hair and declare himself, I know, but that time is not now.", 
     {"entities": []}),
    ("Not to a camp of sellswords.", 
     {"entities": []}),
    ("If Harry Strickland means him ill, hiding him on the Shy Maid will not protect him.", 
     {"entities": [(3, 17, "PERSON"), (42, 50, "LOCATION")]}),
    ("Strickland has ten thousand swords at his command.", 
     {"entities": [(0, 17, "PERSON")]}),
    ("We have Duck.", 
     {"entities": [(10, 14, "PERSON")]}),
    ("Aegon is all that could be wanted in a prince.", 
     {"entities": [(0, 5, "PERSON")]}),
    ("They need to see that, Strickland and the rest.", 
     {"entities": [(0, 17, "PERSON")]}),
]
# train_data = [
#     ("When two of them finally came straggling back to the Wall, it had been as wights.", {"entities": [(34, 38, "LOCATION")]}),
#     ("Not for the first time, or the last, Jon Snow found himself wondering what had become of Benjen Stark.", {"entities": [(31, 39, "PERSON"), (44, 58, "PERSON")]}),
#     ("Dywen would lead one ranging, Black Jack Bulwer and Kedge Whit-eye the other two.", {"entities": [(0, 5, "PERSON"), (20, 38, "PERSON"), (43, 59, "PERSON")]}),
#     ("They at least were eager for the duty.", {"entities": []}),
#     ("Feels good to have a horse under me again, Dywen said at the gate, sucking on his wooden teeth.", {"entities": [(0, 5, "PERSON")]}),
#     ("No man in Castle Black knew the woods as well as Dywen did, the trees and streams, the plants that could be eaten, the ways of predator and prey.", {"entities": [(21, 34, "LOCATION"), (0, 5, "PERSON")]}),
#     ("Thorne is in better hands than he deserves.", {"entities": [(0, 6, "PERSON")]}),
#     ("Jon watched the riders go from atop the Wallthree parties, each of three men, each carrying a pair of ravens.", {"entities": [(0, 3, "PERSON"), (23, 27, "LOCATION")]}),
#     ("From on high their garrons looked no larger than ants, and Jon could not tell one ranger from another.", {"entities": [(14, 17, "PERSON")]}),
#     ("He knew them, though. Every name was graven on his heart.", {"entities": []}),
#     ("Eight good men, he thought, and one well, we shall see.", {"entities": []}),
#     ("When the last of the riders had disappeared into the trees, Jon Snow rode the winch cage down with Dolorous Edd.", {"entities": [(31, 39, "PERSON"), (48, 64, "PERSON")]}),
#     ("A few scattered snowflakes were falling as they made their slow descent, dancing on the gusty wind.", {"entities": []}),
#     ("Jon could have reached through the bars and caught it if he had wished.", {"entities": [(0, 3, "PERSON")]}),
#     ("I had a frightening dream last night, mlord, Dolorous Edd confessed.", {"entities": [(33, 48, "PERSON")]}),
#     ("You were my steward, fetching my food and cleaning up my leavings.", {"entities": []}),
#     ("I was lord commander, with never a moments peace.", {"entities": []}),
#     ("Jon did not smile.", {"entities": [(0, 3, "PERSON")]}),
#     ("Your nightmare, my life.", {"entities": []}),
#     ("Cotter Pykes galleys were reporting ever-increasing numbers of free folk along the wooded shores to the north and east of the Wall.", {"entities": [(0, 14, "PERSON"), (96, 100, "LOCATION")]}),
#     ("Camps had been seen, half-built rafts, even the hull of a broken cog that someone had begun repairing.", {"entities": []}),
#     ("The wildlings always vanished into the woods when seen, no doubt to reemerge as soon as Pykes ships had passed.", {"entities": [(4, 14, "RACE"), (22, 37, "PERSON")]}),
#     ("Meanwhile, Ser Denys Mallister was still seeing fires in the night north of the Gorge.", {"entities": [(16, 38, "PERSON"), (56, 62, "LOCATION")]}),
#     ("Both commanders were asking for more men.", {"entities": []}),
#     ("And where am I to get more men?", {"entities": []}),
#     ("Jon had sent ten of the Moles Town wildlings to each of them: green boys, old men, some wounded and infirm, but all capable of doing work of one sort or another.", {"entities": [(43, 56, "LOCATION"), (60, 71, "RACE")]}),
#     ("Far from being pleased, Pyke and Mallister had both written back to complain.", {"entities": [(60, 64, "PERSON"), (69, 80, "PERSON")]}),
#     ("When I asked for men, I had in mind men of the Nights Watch, trained and disciplined, whose loyalty I should never have reason to doubt, wrote Ser Denys.", {"entities": [(28, 42, "ORG"), (70, 88, "PERSON")]}),
#     ("Cotter Pyke was blunter.", {"entities": [(0, 13, "PERSON")]}),
#     ("I could hang them from the Wall as a warning to other wildlings to stay away, but I dont see any other use for them, Maester Harmune wrote for him.", {"entities": [(49, 53, "LOCATION"), (104, 120, "PERSON")]}),
#     ("I wouldnt trust such to clean my chamber pot, and ten is not enough.", {"entities": []}),
#     ("The iron cage moved downward at the end of its long chain, creaking and rattling, until it finally jerked to a halt a foot above the ground at the base of the Wall.", {"entities": [(33, 37, "LOCATION")]}),
#     ("Dolorous Edd pushed open the door and hopped down, his boots breaking the crust of the last snow.", {"entities": [(0, 16, "PERSON")]}),
#     ("Jon followed.", {"entities": [(0, 3, "PERSON")]}),
#     ("Outside the armory, Iron Emmett was still urging on his charges in the yard.", {"entities": [(25, 39, "PERSON")]}),
#     ("The song of steel on steel woke a hunger in Jon.", {"entities": [(27, 30, "PERSON")]}),
#     ("It reminded him of warmer, simpler days, when he had been a boy at Winterfell matching blades with Robb under the watchful eye of Ser Rodrik Cassel.", {"entities": [(56, 66, "LOCATION"), (70, 75, "PERSON"), (95, 114, "PERSON")]}),
#     ("Ser Rodrik too had fallen, slain by Theon Turncloak and his ironmen as hed tried to retake Winterfell.", {"entities": [(0, 13, "TITLE"), (41, 59, "PERSON"), (76, 85, "LOCATION")]}),
#     ("The great stronghold of House Stark was a scorched desolation.", {"entities": [(36, 45, "HOUSE")]}),
#     ("All my memories are poisoned.", {"entities": []}),
#     ("When Iron Emmett spied him, he raised a hand and combat ceased.", {"entities": [(6, 20, "PERSON")]}),
#     ("Lord Commander. How may we serve you?", {"entities": [("Lord Commander", "TITLE")]}),
#     ("With your three best.", {"entities": []}),
#     ("Emmett grinned. Arron. Emrick. Jace.", {"entities": [(0, 15, "PERSON"), (17, 23, "PERSON"), (25, 29, "PERSON")]}),
#     ("Horse and Hop-Robin fetched padding for the lord commander, along with a ringmail hauberk to go over it, and greaves, gorget, and halfhelm.", {"entities": [("lord commander", "TITLE")]}),
#     ("A black shield rimmed with iron for his left arm, a blunted longsword for his right hand.", {"entities": []}),
#     ("The sword gleamed silvery grey in the dawn light, almost new.", {"entities": []}),
#     ("One of the last to come from Donals forge.", {"entities": [("Donals", "PERSON")]}),
#     ("A pity he did not live long enough to put an edge on it.", {"entities": []}),
#     ("The blade was shorter than Longclaw but made of common steel, which made it heavier.", {"entities": []}),
#     ("It will serve.", {"entities": []}),
#     ("Jon turned to face his foes.", {"entities": [(0, 3, "PERSON")]}),
#     ("Come.", {"entities": []}),
#     ("Which one do you want first?", {"entities": []}),
#     ("asked Arron.", {"entities": [(5, 10, "PERSON")]}),
#     ("All three of you.", {"entities": []}),
#     ("At once.", {"entities": []}),
#     ("Three on one?", {"entities": []}),
#     ("Jace was incredulous.", {"entities": [(0, 4, "PERSON")]}),
#     ("That wouldnt be fair.", {"entities": []}),
#     ("He was one of Conwys latest bunch, a cobblers son from Fair Isle.", {"entities": [(34, 40, "PERSON"), (45, 55, "LOCATION")]}),
# # ]
# # train_data = [
# #     ("Ramsay Bolton had returned and would want his Reek on hand to serve him.", {"entities": [(0, 14, "PERSON"), (44, 48, "PERSON")]}),
# #     ("Outside, beneath a cold autumnal sky, the hunters were pouring through the gates.", {"entities": [("hunters", "OBJECT")]}),
# #     ("Ben Bones led the way, with the girls baying and barking all around him.", {"entities": [("Ben Bones", "PERSON"), ("girls", "OBJECT")]}),
# #     ("Behind came Skinner, Sour Alyn, and Damon Dance-for-Me with his long greased whip,", {"entities": [("Skinner", "PERSON"), ("Sour Alyn", "PERSON"), ("Damon Dance-for-Me", "PERSON")]}),
# #     ("then the Walders riding the grey colts Lady Dustin had given them.", {"entities": [("Walders", "PERSON"), ("Lady Dustin", "PERSON")]}),
# #     ("His lordship himself rode Blood, a red stallion with a temper to match his own.", {"entities": [("lordship", "TITLE"), ("Blood", "OBJECT")]}),
# #     ("He was laughing. That could be very good or very bad, Reek knew.", {"entities": [("Reek", "PERSON")]}),
# #     ("The dogs were on him before he could puzzle out which, drawn to his scent.", {"entities": [("dogs", "OBJECT")]}),
# #     ("The dogs were fond of Reek; he slept with them oft as not, and sometimes Ben Bones let him share their supper.", {"entities": [("Reek", "PERSON"), ("Ben Bones", "PERSON")]}),
# #     ("The pack raced across the flagstones barking, circling him, jumping up to lick his filthy face, nipping at his legs.", {"entities": [("pack", "OBJECT")]}),
# #     ("Helicent caught his left hand between her teeth and worried it so fiercely Reek feared he might lose two more fingers.", {"entities": [("Helicent", "PERSON"), ("Reek", "PERSON")]}),
# #     ("Red Jeyne slammed into his chest and knocked him off his feet.", {"entities": [("Red Jeyne", "PERSON")]}),
# #     ("She was lean, hard muscle, where Reek was loose, grey skin and brittle bones, a white-haired starveling.", {"entities": [("Reek", "PERSON")]}),
# #     ("The riders were dismounting by the time he pushed Red Jeyne off and struggled to his knees.", {"entities": [("riders", "OBJECT"), ("Red Jeyne", "PERSON")]}),
# #     ("Two dozen horsemen had gone out and two dozen had returned, which meant the search had been a failure.", {"entities": [("horsemen", "OBJECT")]}),
# #     ("That was bad. Ramsay did not like the taste of failure.", {"entities": [("Ramsay", "PERSON")]}),
# #     ("He will want to hurt someone.", {"entities": [("someone", "PERSON")]}),
# #     ("Of late, his lord had been forced to restrain himself, for Barrowton was full of men House Bolton needed, and Ramsay knew to be careful around the Dustins and Ryswells and his fellow lordlings.", {"entities": [("Barrowton", "LOCATION"), ("House Bolton", "ORG"), ("Dustins", "PERSON"), ("Ryswells", "PERSON")]}),
# #     ("With them he was always courteous and smiling.", {"entities": []}),
# #     ("What he was behind closed doors was something else.", {"entities": []}),
# #     ("Ramsay Bolton was attired as befit the lord of the Hornwood and heir to the Dreadfort.", {"entities": [("Ramsay Bolton", "PERSON"), ("lord", "TITLE"), ("Hornwood", "LOCATION"), ("Dreadfort", "LOCATION")]})
# # ]
# import spacy
# from spacy.tokens import DocBin
# from spacy.util import minibatch, compounding

# def train_ner_model(train_data, iterations=30):
#     nlp = spacy.blank("en")
#     ner = nlp.add_pipe("ner")
#     for _, annotations in train_data:
#         for ent in annotations.get("entities"):
#             ner.add_label(ent[2])

#     other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
#     with nlp.disable_pipes(*other_pipes):
#         optimizer = nlp.begin_training()
#         for itn in range(iterations):
#             random.shuffle(train_data)
#             losses = {}
#             batches = minibatch(train_data, size=compounding(4., 32., 1.001))
#             for batch in batches:
#                 texts, annotations = zip(*batch)
#                 nlp.update(texts, annotations, drop=0.5, losses=losses)
#             print(f"Iteration {itn}, Losses: {losses}")

#     return nlp

# # Train the model with your domain-specific data

import spacy
from spacy.tokens import DocBin
from spacy.training.example import Example
from spacy.util import minibatch, compounding
import random

def train_ner_model(train_data, iterations=30):
    # Create a blank English model
    nlp = spacy.blank("en")
    # Add the NER pipeline
    ner = nlp.add_pipe("ner")
    # Add entity labels to the NER model
    for _, annotations in train_data:
        for ent in annotations.get("entities"):
            ner.add_label(ent[2])

    # Disable other pipeline components during training
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
    with nlp.disable_pipes(*other_pipes):
        optimizer = nlp.begin_training()
        for itn in range(iterations):
            random.shuffle(train_data)
            losses = {}
            batches = minibatch(train_data, size=compounding(4.0, 32.0, 1.001))
            for batch in batches:
                examples = []
                for text, annotations in batch:
                    # Convert text and annotations into Example objects
                    doc = nlp.make_doc(text)
                    example = Example.from_dict(doc, annotations)
                    examples.append(example)
                # Update the model
                nlp.update(examples, drop=0.5, losses=losses)
            print(f"Iteration {itn}, Losses: {losses}")

    return nlp

import os
import re

def clean_text_file(input_path, output_path):
    """
    Cleans a .txt file extracted from a PDF.
    Args:
        input_path (str): Path to the input .txt file.
        output_path (str): Path to save the cleaned .txt file.
    """
    try:
        with open(input_path, "r", encoding="utf-8") as file:
            text = file.read()
        
        # Remove multiple spaces and newlines
        text = re.sub(r'\s+', ' ', text)

        # Remove non-UTF characters (optional)
        text = re.sub(r'[^\x00-\x7F]+', '', text)

        # Remove page numbers (e.g., patterns like "Page 1" or "1")
        text = re.sub(r'(Page\s?\d+|\b\d+\b)', '', text)

        # Normalize spacing around punctuation
        text = re.sub(r'\s+([.,!?;])', r'\1', text)

        # Convert to lowercase (optional)
        # text = text.lower()

        # Trim leading and trailing spaces
        text = text.strip()

        # Save cleaned text
        with open(output_path, "w", encoding="utf-8") as file:
            file.write(text)

        print(f"Cleaned text saved to {output_path}")
    except Exception as e:
        print(f"Error cleaning file {input_path}: {e}")


# Process all .txt files in a folder
def clean_all_text_files(folder_path):
    """
    Cleans all .txt files in a given folder.
    Args:
        folder_path (str): Path to the folder containing .txt files.
    """
    for filename in os.listdir(folder_path):
        if filename.endswith(".txt"):
            input_path = os.path.join(folder_path, filename)
            output_path = os.path.join(folder_path, f"cleaned_{filename}")
            clean_text_file(input_path, output_path)

# Example usage:
# folder_path = "/Users/anirudhvalluru/Desktop/pypractice/AdvPython/asoiaf copy"  # Folder with your .txt files
# clean_all_text_files(folder_path)

import random

# Sample training data for a custom NER model
# train_data = [
#     ("Google is a leading company in the tech industry.", {"entities": [(0, 6, "ORG")]}),
#     ("Sundar Pichai is the CEO of Google.", {"entities": [(0, 13, "PERSON"), (31, 37, "ORG")]}),
#     ("Microsoft was founded by Bill Gates.", {"entities": [(0, 9, "ORG"), (26, 36, "PERSON")]}),
#     ("Apple and Facebook are competitors.", {"entities": [(0, 5, "ORG"), (10, 18, "ORG")]}),
#     ("Elon Musk is the CEO of SpaceX.", {"entities": [(0, 9, "PERSON"), (29, 35, "ORG")]}),
#     ("IBM, based in Armonk, New York, is an American multinational technology company.",
#      {"entities": [(0, 3, "ORG"), (13, 19, "GPE"), (21, 30, "GPE")]}),
#     ("Amazon operates a massive e-commerce platform.", {"entities": [(0, 6, "ORG")]}),
# ]

# Ensure reproducibility for shuffling during training
random.seed(42)

# You can now pass this train_data to your train_ner_model function.

ner_model = train_ner_model(train_data)
ner_model.to_disk("./domain_ner_model")

import spacy
import networkx as nx

def extract_relationships(doc):
    relationships = []
    for sent in doc.sents:
        root = sent.root
        subject = None
        obj = None
        for child in root.children:
            if child.dep_ == "nsubj":
                subject = child
            if child.dep_ in ["dobj", "pobj"]:
                obj = child
        if subject and obj:
            relationships.append((subject, root, obj))
    return relationships

nlp = spacy.load("./domain_ner_model")

def process_document(text):
    doc = nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    relationships = extract_relationships(doc)
    return entities, relationships

import spacy
import networkx as nx

# Load your model
nlp = spacy.load("./domain_ner_model")

# Add the sentencizer to the pipeline to handle sentence segmentation
if 'sentencizer' not in nlp.pipe_names:
    # Directly add the sentencizer component to the pipeline
    nlp.add_pipe("sentencizer")

def extract_relationships(doc):
    relationships = []
    for sent in doc.sents:
        root = sent.root
        subject = None
        obj = None
        for child in root.children:
            if child.dep_ == "nsubj":
                subject = child
            if child.dep_ in ["dobj", "pobj"]:
                obj = child
        if subject and obj:
            relationships.append((subject, root, obj))
    return relationships

def process_document(text):
    doc = nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    relationships = extract_relationships(doc)
    return entities, relationships

def build_knowledge_graph(documents):
    G = nx.DiGraph()
    for doc in documents:
        entities, relationships = process_document(doc)
        for entity, entity_type in entities:
            G.add_node(entity, type=entity_type)
        for subj, pred, obj in relationships:
            G.add_edge(subj.text, obj.text, relation=pred.text)
    return G

# Split a large text into smaller chunks (by paragraphs, sentences, etc.)
def chunk_text(text, chunk_size=1000):  # Adjust chunk_size based on your needs
    chunks = []
    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i+chunk_size])
    return chunks

# Load the book as a string (assuming 'book.txt' is the full book)
with open("./cleaned_GOT2.txt", "r", encoding="utf-8") as file:
    full_text = file.read()

# Split the book into chunks
chunks = chunk_text(full_text)

# Process the chunks and build the knowledge graph
knowledge_graph = build_knowledge_graph(chunks)

# Visualize the graph or use it for further analysis
import matplotlib.pyplot as plt
nx.draw(knowledge_graph, with_labels=True, node_color="skyblue", edge_color="gray")
plt.show()
